# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: item_db.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ritem_db.proto\"\x1e\n\x06ItemDB\x12\x14\n\x05items\x18\x01 \x03(\x0b\x32\x05.Item\"Z\n\x04Item\x12 \n\x0bitem_string\x18\x01 \x01(\x0b\x32\x0b.ItemString\x12\x30\n\x14market_value_records\x18\x02 \x03(\x0b\x32\x12.MarketValueRecord\"T\n\nItemString\x12\x1d\n\x04type\x18\x01 \x01(\x0e\x32\x0f.ItemStringType\x12\n\n\x02id\x18\x02 \x01(\x05\x12\r\n\x05\x62onus\x18\x03 \x03(\x05\x12\x0c\n\x04mods\x18\x04 \x03(\x05\"f\n\x11MarketValueRecord\x12\x11\n\ttimestamp\x18\x01 \x01(\x05\x12\x14\n\x0cnum_auctions\x18\x02 \x01(\x05\x12\x14\n\x0cmarket_value\x18\x03 \x01(\x03\x12\x12\n\nmin_buyout\x18\x04 \x01(\x03*#\n\x0eItemStringType\x12\x08\n\x04ITEM\x10\x00\x12\x07\n\x03PET\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'item_db_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ITEMSTRINGTYPE._serialized_start=331
  _ITEMSTRINGTYPE._serialized_end=366
  _ITEMDB._serialized_start=17
  _ITEMDB._serialized_end=47
  _ITEM._serialized_start=49
  _ITEM._serialized_end=139
  _ITEMSTRING._serialized_start=141
  _ITEMSTRING._serialized_end=225
  _MARKETVALUERECORD._serialized_start=227
  _MARKETVALUERECORD._serialized_end=329
# @@protoc_insertion_point(module_scope)
