name: Test
'on':
  workflow_call:
    inputs:
      upload-coverage:
        description: Upload coverage reports to Codecov
        required: false
        default: false
        type: boolean
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: pip
    # python<3.11 needs coverage[toml] to parse pyproject.toml
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage[toml]
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Unittest
      run: |
        python -m coverage run -m unittest discover -vfs tests
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      if: ${{ inputs.upload-coverage == true }}
